apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      tier: backend
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP