apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: nginx
    tier: backend
spec:
  containers:
    - name: redis
      image: redis
      imagePullPolicy: IfNotPresent
      ports:
        - name: redis
          containerPort: 80
          protocol: TCP
  restartPolicy: Always
  